from manyfunction import *
clear()
from mylibral import *
menus=[
["ファイル",
["開く",
[["SubmenuのMenu"],"メニュー2",["メニュー2のMenu"],"メニュー3","メニュー4"],
"---",
{"label":"閉じる","function":lambda:win.root.quit()}
]
],
["ヘルプ",
[
{"label":"バージョン"}
]
]
]
list_val=["赤","青","黄"]
list_val2=["赤","青","黄","赤","青","黄","赤","青","黄","赤","青","黄"]
tree_values=[
"あ行",["あ","い","う","え","お"],
"か行",["か","き","く","け","こ"],
"が行",["が","ぎ","ぐ","げ","ご"]
]
def txtchange():win.get("txt1").set_text("!!!変わった!!!")
def files():sgg.Popup(message=win.get("file_load")._choose_pas())
def folders():sgg.Popup(message=win.get("folder_load")._choose_pas())
def colors():sgg.Popup(message=win.get("color_select")._choose_color())
def progress_start():win.get("prigress")._start()
layout=[
[sgg.Menu(list=menus,key="menus")],
[sgg.Text(text="Textウィジェット")],
[sgg.Text(text="keyがtxt1のTextウィジェット",key="txt1"),
sgg.Text(key="txt2",text="文字色が水色,背景色が赤色,\nサイズが30文字の幅で高さが3文字分の\nTextウィジェット",
bg="red",fg="aqua",size=(30,3))
],
[sgg.Button(text="ボタンウィジェット",key="btn1")],
[sgg.Text(text="keyがtxt1のTextのテキストを変えるボタン->"),
sgg.Button(text="!!変える!!",function=[txtchange],key="btn2")],
[sgg.Link(link="https://www.google.com/",text="googleのサイトを開く")],
[sgg.Images(path="img.png")],
[sgg.Text(text="↑画像表示(PGM,PPM,GIF,PNG,XBMでしか表示されない)")],
[sgg.Images(path="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg48GxlSXF_4b4XZmtOALPhe3mD5iREyN-Ks6Q2hdviWeDHOcG_AUOS3nn2i-E9g5jD1_7-2o9PZF5MUQEanceM7b07viAr9M6h4C7jDqGhKdF0LzHzn2IBS_A2Fvpv605wIRf9ohIPiv-HStNDjk8JdN2hU-0GTI-OsjRraMo1HnGkTALf6v7qBbHufj04/s400/pose_galpeace_schoolgirl.png")],
[sgg.Text(text="↑URLで指定された画像ファイルは読み取れない")],
[sgg.Text(text="入力欄->"),sgg.Input(text="入力欄")],
[sgg.Text(text="パスワード入力->"),sgg.Input(show="※")],
[sgg.Text(text="複数行表示できる入力欄")],
[sgg.Multiline(text="複数行表示可能の入力欄",key="multiline1"),sgg.Multiline(text=["配列でも","表示可能"],key="multiline2")],
[sgg.Text(text="赤に選択されたリストボックス")],
[sgg.Listbox(values=list_val,select=0)],
[sgg.Combobox(values=list_val,default="好きな色を選ぼう!")],
[sgg.Text(text="数値入力")],
[sgg.InputNumber(key="number")],
[sgg.Text(text="スクロールを追加する")],
[
sgg.Input(text="こんにちは。初めまして。",width=10,scroll_x=True),
sgg.Multiline(text=[1,2,3,4,5,6,7,8,9,10],size=(10,5),scroll_x=True,scroll_y=True,key="multiline1"),
sgg.Listbox(values=list_val2,select=0,scroll_y=True)
],
[sgg.Text(text="この中で一番好きな色を一つ選ぶ")],
[
sgg.Radio(text="赤色",group="color_name"),
sgg.Radio(text="黄色",group="color_name"),
sgg.Radio(text="緑色",group="color_name"),
sgg.Radio(text="黒色",group="color_name"),
sgg.Radio(text="その他",group="color_name")
],
[sgg.Text(text="この中で一番好きな色を複数選ぶ")],
[
sgg.Checkbox(text="赤色",group="color_name"),
sgg.Checkbox(text="黄色",group="color_name"),
sgg.Checkbox(text="緑色",group="color_name"),
sgg.Checkbox(text="黒色",group="color_name"),
sgg.Checkbox(text="その他",group="color_name")
],
[sgg.Text(text="この中で一番好きな食べ物を一つ選ぶ")],
[
sgg.Radio(text="からあげ",group="food_name"),
sgg.Radio(text="蕎麦",default=True,group="food_name"),
sgg.Radio(text="おすし",group="food_name"),
sgg.Radio(text="おにぎり",group="food_name"),
sgg.Radio(text="その他",group="food_name")
],
[sgg.Text(text="この中で一番好きな食べ物を複数選ぶ")],
[
sgg.Checkbox(text="からあげ",group="food_name"),
sgg.Checkbox(text="蕎麦",default=True,group="food_name"),
sgg.Checkbox(text="おすし",group="food_name"),
sgg.Checkbox(text="おにぎり",group="food_name"),
sgg.Checkbox(text="その他",group="food_name")
],
[sgg.Text(text="ファイルを選ぶ")],
[sgg.FileLoad(key="file_load")],
[sgg.Button(function=[files],text="選択したファイル")],
[sgg.Text(text="フォルダを選ぶ")],
[sgg.FolderLoad(key="folder_load")],
[sgg.Button(text="選択したフォルダ",function=[folders])],
[sgg.Text(text="色を選ぶ")],
[sgg.Colorbtn(key="color_select")],
[sgg.Button(text="選択した色",function=[colors])],
[sgg.Text(text="タブ")],
[sgg.Tab(tabs=[
["tab1",[[sgg.Text(text="tab1")]]],
["tab2",[[sgg.Text(text="tab2")]]]
],key="tabs1")],
[sgg.Text(text="カレンダー")],
[sgg.Calendars(key="cal")],
[sgg.Text(text="日付を選択する")],
[sgg.InputDate(key="inputcal")],
[sgg.Text(text="スライダー")],
[sgg.Slidebar(value=20)],
[sgg.Text(text="プログレスバー")],
[sgg.Progressbar(key="prigress")],
[sgg.Text(text="表(縦見出しあり)")],
[sgg.Table(header=["列A","列B"],values=[["r1c1","r1c2"],["r2c1","r2c2"]],rowheader=["aa","bb"],key="table1")],
[sgg.Text(text="表(縦見出しなし)")],
[sgg.Table(header=["列A","列B"],values=[["r1c1","r1c2"],["r2c1","r2c2"]],key="table2")],
[sgg.Text(text="ツリー")],
[sgg.Tree(values=tree_values,side_header="行",header=["あ","い","う","え","お"],key="tree1")],
[sgg.Text(text="メニューボタン")],
[sgg.Menubutton(list=menus)],
[sgg.Button(text="Popup(情報)",function=lambda:print(sgg.Popup(message="メッセージ")))],
[sgg.Button(text="Popupwarning(注意)",function=lambda:print(sgg.Popupwarning(message="メッセージ")))],
[sgg.Button(text="Popupwarningyesno(注意)",function=lambda:print(sgg.Popupwarningyesno(message="メッセージ")))],
[sgg.Button(text="Popuperror(エラー)",function=lambda:print(sgg.Popuperror(message="メッセージ")))],
[sgg.Button(text="Popupyesno(bool型を返す)",function=lambda:print(sgg.Popupyesno(message="メッセージ")))],
[sgg.Button(text="Popupokcancel(bool型を返す)",function=lambda:print(sgg.Popupokcancel(message="メッセージ")))],
[sgg.Button(text="Popupquestion(YesかNoを返す)",function=lambda:print(sgg.Popupquestion(message="メッセージ")))],
[sgg.Button(text="Popupyesnocancel(bool型とNoneを返す)",function=lambda:print(sgg.Popupyesnocancel(message="メッセージ")))],
[sgg.Button(text="Popuptrycancel(bool型を返す)",function=lambda:print(sgg.Popuptrycancel(message="メッセージ")))]
]
win=sgg.window(title="mylibral ウィジェット デモ",layout=layout,load=progress_start,scroll_x=True,scroll_y=True,maxmine=True)
win.run()